apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: webapplication-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: movies.local
      http:
        paths:
          - path: /(.*)
            backend:
              serviceName: webapp-k8s-service
              servicePort: 80
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: backend-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: movies.local
      http:
        paths:
          - path: /movies(?:/|$)(.*)
            backend:
              serviceName: movies-k8s-service
              servicePort: 3000