// Code generated by protoc-gen-go. DO NOT EDIT.
// source: recommendation.proto

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	recommendation.proto

It has these top-level messages:
	Movie
	Results
	Result
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type Movie struct {
	MovieID int32 `protobuf:"varint,1,opt,name=movieID" json:"movieID,omitempty"`
}

func (m *Movie) Reset()                    { *m = Movie{} }
func (m *Movie) String() string            { return proto1.CompactTextString(m) }
func (*Movie) ProtoMessage()               {}
func (*Movie) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Movie) GetMovieID() int32 {
	if m != nil {
		return m.MovieID
	}
	return 0
}

type Results struct {
	Results []*Result `protobuf:"bytes,1,rep,name=results" json:"results,omitempty"`
}

func (m *Results) Reset()                    { *m = Results{} }
func (m *Results) String() string            { return proto1.CompactTextString(m) }
func (*Results) ProtoMessage()               {}
func (*Results) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Results) GetResults() []*Result {
	if m != nil {
		return m.Results
	}
	return nil
}

type Result struct {
	VoteAverage  float32 `protobuf:"fixed32,1,opt,name=VoteAverage,json=vote_average" json:"VoteAverage,omitempty"`
	ID           int64   `protobuf:"varint,2,opt,name=ID,json=id" json:"ID,omitempty"`
	ReleaseDate  string  `protobuf:"bytes,3,opt,name=ReleaseDate,json=release_date" json:"ReleaseDate,omitempty"`
	BackdropPath string  `protobuf:"bytes,4,opt,name=BackdropPath,json=backdrop_path" json:"BackdropPath,omitempty"`
	Title        string  `protobuf:"bytes,5,opt,name=Title,json=title" json:"Title,omitempty"`
	PosterPath   string  `protobuf:"bytes,6,opt,name=PosterPath,json=poster_path" json:"PosterPath,omitempty"`
	Overview     string  `protobuf:"bytes,7,opt,name=Overview,json=overview" json:"Overview,omitempty"`
}

func (m *Result) Reset()                    { *m = Result{} }
func (m *Result) String() string            { return proto1.CompactTextString(m) }
func (*Result) ProtoMessage()               {}
func (*Result) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Result) GetVoteAverage() float32 {
	if m != nil {
		return m.VoteAverage
	}
	return 0
}

func (m *Result) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *Result) GetReleaseDate() string {
	if m != nil {
		return m.ReleaseDate
	}
	return ""
}

func (m *Result) GetBackdropPath() string {
	if m != nil {
		return m.BackdropPath
	}
	return ""
}

func (m *Result) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Result) GetPosterPath() string {
	if m != nil {
		return m.PosterPath
	}
	return ""
}

func (m *Result) GetOverview() string {
	if m != nil {
		return m.Overview
	}
	return ""
}

func init() {
	proto1.RegisterType((*Movie)(nil), "proto.Movie")
	proto1.RegisterType((*Results)(nil), "proto.Results")
	proto1.RegisterType((*Result)(nil), "proto.Result")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Recommendation service

type RecommendationClient interface {
	GetRecommendations(ctx context.Context, in *Movie, opts ...grpc.CallOption) (*Results, error)
}

type recommendationClient struct {
	cc *grpc.ClientConn
}

func NewRecommendationClient(cc *grpc.ClientConn) RecommendationClient {
	return &recommendationClient{cc}
}

func (c *recommendationClient) GetRecommendations(ctx context.Context, in *Movie, opts ...grpc.CallOption) (*Results, error) {
	out := new(Results)
	err := grpc.Invoke(ctx, "/proto.Recommendation/GetRecommendations", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Recommendation service

type RecommendationServer interface {
	GetRecommendations(context.Context, *Movie) (*Results, error)
}

func RegisterRecommendationServer(s *grpc.Server, srv RecommendationServer) {
	s.RegisterService(&_Recommendation_serviceDesc, srv)
}

func _Recommendation_GetRecommendations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Movie)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecommendationServer).GetRecommendations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Recommendation/GetRecommendations",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecommendationServer).GetRecommendations(ctx, req.(*Movie))
	}
	return interceptor(ctx, in, info, handler)
}

var _Recommendation_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Recommendation",
	HandlerType: (*RecommendationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetRecommendations",
			Handler:    _Recommendation_GetRecommendations_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "recommendation.proto",
}

func init() { proto1.RegisterFile("recommendation.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 286 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0x31, 0x6f, 0xfa, 0x30,
	0x10, 0xc5, 0xe5, 0xf0, 0x37, 0xe1, 0x7f, 0x04, 0x06, 0x8b, 0xc1, 0x62, 0x69, 0xa0, 0x43, 0x33,
	0x31, 0xa4, 0x9f, 0xa0, 0x55, 0xa4, 0x8a, 0xa1, 0x2a, 0xb2, 0xaa, 0xae, 0xc8, 0x90, 0x53, 0x89,
	0x9a, 0xe0, 0xc8, 0xbe, 0xa6, 0xdf, 0xb4, 0x9f, 0xa7, 0x8a, 0x1d, 0x86, 0x4c, 0x77, 0xef, 0xf7,
	0xee, 0xdd, 0xf0, 0x60, 0x65, 0xf1, 0x6c, 0x9a, 0x06, 0xaf, 0xa5, 0xa6, 0xca, 0x5c, 0x77, 0xad,
	0x35, 0x64, 0x04, 0xf7, 0x63, 0xbb, 0x01, 0xfe, 0x6a, 0xba, 0x0a, 0x85, 0x84, 0xb8, 0xe9, 0x97,
	0x7d, 0x21, 0x59, 0xca, 0x32, 0xae, 0x6e, 0x72, 0x9b, 0x43, 0xac, 0xd0, 0x7d, 0xd7, 0xe4, 0xc4,
	0x03, 0xc4, 0x36, 0xac, 0x92, 0xa5, 0x93, 0x6c, 0x9e, 0x2f, 0xc2, 0xb7, 0x5d, 0x38, 0x50, 0x37,
	0x77, 0xfb, 0xcb, 0x60, 0x1a, 0x98, 0xd8, 0xc0, 0xfc, 0xc3, 0x10, 0x3e, 0x75, 0x68, 0xf5, 0x27,
	0xfa, 0xe7, 0x91, 0x4a, 0x3a, 0x43, 0x78, 0xd4, 0x81, 0x89, 0x25, 0x44, 0xfb, 0x42, 0x46, 0x29,
	0xcb, 0x26, 0x2a, 0xaa, 0xca, 0x3e, 0xa2, 0xb0, 0x46, 0xed, 0xb0, 0xd0, 0x84, 0x72, 0x92, 0xb2,
	0xec, 0xbf, 0x4a, 0x6c, 0x40, 0xc7, 0x52, 0x13, 0x8a, 0x7b, 0x48, 0x9e, 0xf5, 0xf9, 0xab, 0xb4,
	0xa6, 0x3d, 0x68, 0xba, 0xc8, 0x7f, 0xfe, 0x66, 0x71, 0x1a, 0xd8, 0xb1, 0xd5, 0x74, 0x11, 0x2b,
	0xe0, 0xef, 0x15, 0xd5, 0x28, 0xb9, 0x77, 0x39, 0xf5, 0x42, 0xdc, 0x01, 0x1c, 0x8c, 0x23, 0xb4,
	0x3e, 0x38, 0xf5, 0xd6, 0xbc, 0xf5, 0x24, 0xc4, 0xd6, 0x30, 0x7b, 0xeb, 0xd0, 0x76, 0x15, 0xfe,
	0xc8, 0xd8, 0xdb, 0x33, 0x33, 0xe8, 0xbc, 0x80, 0xa5, 0x1a, 0xd5, 0x29, 0x72, 0x10, 0x2f, 0x48,
	0x63, 0xe8, 0x44, 0x32, 0x14, 0xe3, 0xcb, 0x5d, 0x2f, 0x47, 0x35, 0xb9, 0xd3, 0xd4, 0xcb, 0xc7,
	0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x5f, 0x95, 0x97, 0xb6, 0x9b, 0x01, 0x00, 0x00,
}
